- title: Public speaking
  icon: "/services/speaking.svg"
  description: Loves sharing knowledge
- title: Blogging
  icon: "/services/blogging.svg"
  description: Active blogger
- title: Web Development
  icon: "/services/webdev.svg"
  description: In love with web technologies
- title: Internet of Things (IoT)
  icon: "/services/smart-home.svg"
  description: He likes things smart
